name: Erlang CI

on:
  push:
    branches:
      - nhse-develop
      - nhse-develop-3.2
      - nhse-develop-3.4
  pull_request:
    branches:
      - nhse-develop
      - nhse-develop-3.2
      - nhse-develop-3.4


jobs:

  build:

    name: Test on ${{ matrix.os }} with OTP ${{ matrix.otp }}
    runs-on: ${{ matrix.os }}

    container:
      image: erlang:${{matrix.otp}}

    strategy:
      fail-fast: false
      matrix:
        otp: [24, 26]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Compile
        run: ./rebar3 compile
      - name: Run xref and dialyzer
        run: ./rebar3 do xref, dialyzer
      - name: Run eunit
        run: ./rebar3 as gha do eunit
